apiVersion: apps/v1
kind: Deployment
metadata:
  name: neorent-deployment
  namespace: neorent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neorent
  template:
    metadata:
      labels:
        app: neorent
    spec:
      containers:
        - name: neorent-app
          image: lionel1109/neorent:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
