apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: neorent-hpa
  namespace: neorent
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: neorent
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60  # Déclenche le scale-up si l'utilisation CPU > 60%
