# neorent-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neorent
  namespace: neorent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neorent
  template:
    metadata:
      labels:
        app: neorent
    spec:
      containers:
        - name: neorent
          image: lionel1109/neorent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
