apiVersion: apps/v1
kind: Deployment
metadata:
  name: neorent-deployment
  namespace: neorent
  labels:
    app: neorent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neorent
  template:
    metadata:
      labels:
        app: neorent
    spec:
      containers:
        - name: neorent-container
          image: lionel1109/neorent:latest
          ports:
            - containerPort: 443
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/ssl/certs
              readOnly: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: tls-certs
          secret:
            secretName: neorent-tls
