apiVersion: apps/v1
kind: Deployment
metadata:
  name: neorent-app
  namespace: neorent
  labels:
    app: neorent
spec:
  replicas: 3 # Scalabilité (ajuster selon besoin)
  selector:
    matchLabels:
      app: neorent
  template:
    metadata:
      labels:
        app: neorent
    spec:
      containers:
      - name: neorent-container
        image: lionel1109/neorent:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"      # CPU demandé
            memory: "256Mi"  # Mémoire demandée
          limits:
            cpu: "500m"      # CPU limite
            memory: "512Mi"  # Mémoire limite
