apiVersion: v1
kind: Service
metadata:
  name: neorent-service
  namespace: neorent
spec:
  selector:
    app: neorent
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
  type: NodePort
