apiVersion: v1
kind: Service
metadata:
  name: neorent-service
  namespace: neorent
spec:
  selector:
    app: neorent
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080  # ou ce que ton app utilise
  type: ClusterIP
