apiVersion: v1
kind: Service
metadata:
  name: neorent-service
  namespace: neorent
spec:
  type: NodePort
  selector:
    app: neorent
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 33443 # Tu peux choisir un port entre 30000 et 32767
